name: kraken2_workflow
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake-minimal>=7.0
  - fastp
  - bowtie2
  - samtools
  - kraken2
  - bracken
  - krakentools
  - multiqc